[package]
name = "sgx_rand"
version = "0.9.0"
authors = ["Baidu"]

[features]
default = []

[dependencies]
sgx_types = { path = "../sgx_types" }
sgx_trts = { path = "../sgx_trts" }
sgx_tstd = { path = "../sgx_tstd" }

