[package]
name = "Hugememsampleenclave"
version = "0.1.0"
authors = ["Baidu"]

[lib]
name = "hugememsampleenclave"
crate-type = ["staticlib"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_trts = { path = "../../../sgx_trts" }
