[package]
name = "Hugememsampleenclave"
version = "0.9.1"
authors = ["Baidu"]

[lib]
name = "hugememsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
