[package]
name = "enclave2"
version = "0.9.1"
authors = ["Baidu"]

[lib]
name = "enclave2"
crate-type = ["staticlib"]


[features]
default = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
attestation = {path = "../attestation/"}