[package]
name = "sgx_tstd"
version = "0.9.5"
authors = ["Baidu"]
build = "build.rs"

[lib]
name = "sgx_tstd"
crate-type = ["rlib"]

[features]
default = ["backtrace"]
backtrace = ["stdio"]
stdio = []

[build-dependencies]
build_helper = { path = "../build_helper" }

[dependencies]
sgx_types = { path = "../sgx_types" }
sgx_trts = { path = "../sgx_trts" }
sgx_alloc = { path = "../sgx_alloc" }
sgx_tprotected_fs = { path = "../sgx_tprotected_fs" }
unwind = { path = "../libunwind" }
