[package]
name = "Thread sample enclave"
version = "0.9.0"
authors = ["Baidu"]

[lib]
name = "enclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_tstd = { path = "../../../sgx_tstd" }
