[package]
name = "Thread sample enclave"
version = "0.1.0"
authors = ["Baidu"]

[lib]
name = "enclave"
crate-type = ["staticlib"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_trts = { path = "../../../sgx_trts" }
sgx_tstdc = { path = "../../../sgx_tstdc" }
