[package]
name = "attestation"
version = "0.9.1"
authors = ["Baidu"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_tdh = { path = "../../../sgx_tdh" }
