[package]
name = "enclave1"
version = "0.1.0"
authors = ["Baidu"]

[lib]
name = "enclave1"
crate-type = ["staticlib"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tdh = { path = "../../../sgx_tdh" }
attestation = {path = "../attestation/"}