[package]
name = "enclave1"
version = "0.9.1"
authors = ["Baidu"]

[lib]
name = "enclave1"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
attestation = {path = "../attestation/"}