[package]
name = "sgx_cov"
version = "0.1.0"
authors = ["MesaTEE Authors"]
description = "Enabling gcov for SGX crates."
edition = "2018"

include = [
    "./lib.rs",
    "./Readme.md",
    "./Cargo.toml",
    "./fake_profiler_builtins/lib.rs",
    "./fake_profiler_builtins/Cargo.toml",
]

[lib]
name = "sgx_cov"
path = "lib.rs"

[dependencies]
lazy_static = { version = "1", features = ["spin_no_std"] }

[target.'cfg(target_env = "sgx")'.dependencies]
profiler_builtins = { path = "fake_profiler_builtins" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { path = "../sgx_types" }
sgx_tstd    = { path = "../sgx_tstd" }
sgx_rand    = { path = "../sgx_rand" }
