[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []


[dependencies]
kvdb = { path = "../../../third_party/parity-common/kvdb" }
kvdb-memorydb = { path = "../../../third_party/parity-common/kvdb-memorydb" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
