[package]
name = "Machinelearningsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "machinelearningsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_types = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_rand = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }

[dependencies]
rusty-machine = { git = "https://github.com/mesalock-linux/rusty-machine-sgx" }
serde         = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json    = { git = "https://github.com/mesalock-linux/serde-json-sgx" }
