[package]
name = "sgx_tseal"
version = "0.1.0"
authors = ["Baidu"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../sgx_types" }
sgx_trts = { path = "../sgx_trts" }
sgx_tcrypto = { path = "../sgx_tcrypto" }
sgx_tse = { path = "../sgx_tse" }
