[package]
name = "tr-mpc-client"
version = "0.1.0"
authors = ["Webb Shi <bradyjoestar@gmail.com>"]

[dependencies]
chrono      = "0.4.5"
webpki      = "0.18.1"
rustls      = { version = "0.13.0", features = ["dangerous_configuration"] }
itertools   = "*"
sgx_types   = { path = "../../../sgx_types" }
base64      = "0.9.2"
untrusted   = "0.6.2"
serde_json  = "1.0.24"
num-bigint  = "*"
bit-vec     = "*"
hex         = "*"
