[package]
name = "sgx_tservice"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "sgx_tservice"
crate-type = ["rlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "../sgx_types" }
