[package]
name = "enclave3"
version = "0.9.0"
authors = ["Baidu"]

[lib]
name = "enclave3"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
attestation = {path = "../attestation/"}