[package]
name = "sgx_tunittest"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "sgx_tunittest"
crate-type = ["rlib"]

[features]
default = []

[dependencies]
sgx_tstd = { path = "../sgx_tstd" }
